version: '3.3'
services:
  app-dev:
    build:
      context: .
      dockerfile: devcontainer.dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      TZ=Asia: Tokyopp
      LOCAL_URI: mongodb://root:example@mongo:27017
    env_file: devcontainer.env
    networks:
      - mongo_network
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo:latest
    networks:
      - mongo_network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    tty: true
    ports:
      - 27017:27017
    volumes:
      - ../tmp/mongo/db:/data/db
      - ../tmp/mongo/configdb:/data/configdb

  mongo-express:
    image: mongo-express:latest
    networks:
      - mongo_network
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

networks:
  mongo_network:
